name: agriplant
description: Agriculture plant app
publish_to: "1"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  animate_do: ^3.3.3
  flutter_riverpod: ^2.5.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  dio: any
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.8
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  intl: ^0.19.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  cached_network_image: ^3.4.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.1.2
  uuid: ^4.5.1
  printing: ^5.13.3
  pdf: ^3.11.1
  collection: ^1.18.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - shorebird.yaml
